repos:
-   repo: https://github.com/dvolgyes/template-commit-msg
    rev: 'v0.1'
    hooks:
    -   id: template-commit-msg
        # use starting # to indicate 'empty by default'
        args: ['--pattern=#[] ... (#)']
        stages: ['prepare-commit-msg']
-   repo: local
    hooks:
    # e.g. [add] or [remove]
    -   id: commit-type-field
        name: check for qualifier field
        language: pygrep
        entry: '\A\[[a-zA-Z]+\]'
        args: ["--multiline", "--negate"]
        stages: [commit-msg]
-   repo: local
    hooks:
    # e.g. #7
    -   id: issue-number-check
        name: check for issue number
        language: pygrep
        entry: '#[0-9]+'
        args: ["--multiline", "--negate"]
        stages: [commit-msg]
