-   id: template-commit-msg
    name: "template-commit-msg"
    description: "Template for commit messages"
    entry: template-commit-msg
    always_run: true
    language: python
    stages: ['prepare-commit-msg']
    minimum_pre_commit_version: "1.16"
